### ISSUE TITLE
A few questions I'm asking, I hope you don't mind.

### ISSUE THREAD

**Issue by 9211tr** [RoadrunnerWMC/BRFNTify-Next#1]
Since RVLution is down, and nobody can access the thread (the "BRFNTify Next" thread), will you provide the download for the "compiled/binary" version (a Windows EXE) which was on the thread, either by providing the download link to it (probably in the "README"), or by [drafting a "release" on this repository?](https://help.github.com/articles/creating-releases/)

Also, slightly off-topic: Since RVLution is down for about 1 year and nothing is archived, how is the RVLution archive going? Did you just lost motivation on it?

**Comment by RoadrunnerWMC** [comment]
[There you go.](https://github.com/RoadrunnerWMC/BRFNTify-Next/releases/tag/v0.1)

General note to anyone who stumbles upon this issue in the future: anything that I've ever released but didn't put on Github still lives in my Dropbox; I'll move such things onto Github if anyone asks.

About your second question: Yeah, pretty much. I keep putting it off until after this or that long-term project, and never actually get around to doing it. People do still occasionally ask me to retrieve stuff from it, though (which I can't really do without actually setting up the archive, unfortunately), which tells me there is still interest.
